###                                                     
POST http://localhost:5000/api/v1/register
Content-Type: application/json

{
    "username": "indah",
    "password": "indah",
    "fullname": "indah",
    "isAdmin": 0,
    "gender": "wanita",
    "email": "indah@gmail.com",
    "phone": "08123456789",
    "idKamar": "89bd49f4-7da2-11f1-b66a-088fc3800c67",
    "tanggalMasuk": "2026-07-12"
}

###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###
GET http://localhost:5000/api/v1/logout

###
GET http://localhost:5000/api/v1/getMe

# ---------------------------------------- Kost -----------------------------------------------
###
GET http://localhost:5000/api/v1/kost

###
GET http://localhost:5000/api/v1/detailKost

###
POST http://localhost:5000/api/v1/kost
Content-Type: application/json

{
    "name": "Kost Batam Center 2",
    "lokasi": "Jl. Bukit Palem Permai No.2B, Belian, Kec. Batam Kota, Kota Batam, Kepulauan Riau 29464",
    "jumlahKamar": 24
}

###
PATCH http://localhost:5000/api/v1/kost/506d1e16-874e-4437-a177-a0376b27c409
Content-Type: application/json

{
    "name": "kost A",
    "lokasi": "kost A",
    "jumlahKamar": 10
}

###
DELETE http://localhost:5000/api/v1/kost/30aa98a1-7b67-4ec3-b37c-6e1a60567ead

